### ISSUE TITLE
`sarima_reg` parameters

### ISSUE THREAD

**Issue by spsanderson** [AlbertoAlmuinha/bayesmodels#10]
@AlbertoAlmuinha  Is it mandatory that the seasonal parameters be known beforehand for the `sarima_reg` or will the algorithm take what you give and adjust?

**Comment by AlbertoAlmuinha** [comment]
No, you need to enter them beforehand, there is no automatic version of the algorithm, at least for the moment.

**Comment by spsanderson** [comment]
Ok thank you

Sent from my iPhone
www.spsanderson.com
