### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by lg1000** [AlbertoAlmuinha/bayesmodels#13]
I am just trying to install your package with no success. I did try on mac and on windows 10 under R version 4.1.1 and 4.1.2. When I try to install via cran it states, that this package is not available for my version of R.

When I try to install the development version, I get the following error:
<img width="780" alt="BAYES_ERROR" src="https://user-images.githubusercontent.com/27286618/156897976-4cb32cfc-f5f9-4e8d-8e22-ad673a4b375e.png">

Restarting R did not help.

**Comment by RodrigoZepeda** [comment]
Try updating `cli` first: `update.packages("cli")`.

**Comment by AlbertoAlmuinha** [comment]
Yeah, you should update `cli` first as Rodrigo told.
