### ISSUE TITLE
Package can't be installed

### ISSUE THREAD

**Issue by GreyMerchant** [AlbertoAlmuinha/bayesmodels#16]
Hi there,

Last time I used this package it was still on cran. I tried to install from here but not having any luck. The error is also kinda non descriptive. Any advice or help?

![image](https://user-images.githubusercontent.com/39332355/183247591-06d0b315-2513-4589-bfb2-4cf3eb853905.png)

**Comment by AlbertoAlmuinha** [comment]
Can you try now??

It was an error due to a new update of parsnip package

**Comment by GreyMerchant** [comment]
Thanks for the update. I'll give it a go!

**Comment by AlbertoAlmuinha** [comment]
I will close the issue. Let me know if you can't install it anyway!
